spring:
  application:
    name: web2
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    enabled: true   # Swagger UI 활성화
    path: /swagger-ui.html  # Swagger UI 접속 경로
    operations-sorter: method  # 메서드 기준 정렬
    tags-sorter: alpha  # 태그를 알파벳순으로 정렬
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서의 기본 경로 설정
  show-actuator: true  # Actuator 관련 문서도 Swagger에서 표시